eps: 0.001
#eval_mode: False
eval_mode: True
use_diffmot: False

# optimizer
lr: 0.0001
# train
data_dir: "/data/zelinliu/sportsmot/trackers_gt_t"
diffnet: HMINet
interval: 5
augment: True
encoder_dim: 256
tf_layer: 3
epochs: 1000
batch_size: 2048
seed: 123
eval_every: 20
gpus: [0,]

# Testing
eval_at: 340 #
det_dir: "/data/zelinliu/sportsmot/detections/val"
info_dir: "/data/zelinliu/sportsmot/val"
reid_dir: "/data/zelinliu/TrackSSM/cache/embeddings/"
save_dir: "/data/zelinliu/TrackSSM/results/val/yolox_m_lt_ddm_1000eps_deeper_340_ept"
eval_expname: lt_ddm_1000_deeper
show_image: False
use_detection_model: False
det_ckpt: "SportsMOT_yolox_x.tar"
exp_path: "external/YOLOX/exps/sportsmot/yolox_x_sportsmot_mix.py"
high_thres: 0.6
low_thres: 0.1
w_assoc_emb: 2.0
aw_param: 1.2
preprocess_workers: 16

# Data Parameters:
device: cuda
eval_device: None
